<?php 

$perpage = '{
    "status": 1,
    "message": "Success",
    "data": [
        {
            "_id": 517826,
            "OStatus": 17,
            "WOStatus": 17,
            "odid": "DG-DI-19-745506",
            "wodid": "WO-000-19-58940141",
            "wid": 479537,
            "order": {
                "patientinfo": {
                    "mrn": "275238",
                    "patient_id": "312766",
                    "name": "chsis  allocate",
                    "age": "39Y",
                    "gender": "2",
                    "contact": "7064724111",
                    "landmark": "Home",
                    "pincode": "500050",
                    "address": "chiss",
                    "city": "Hyderabad",
                    "popname": "MADINAGUDA - SUPER POP",
                    "delivery_lat": "17.497764600000000000",
                    "delivery_lng": "78.331686200000000000",
                    "scheduled_date": "2019-02-19T11:11:00.000Z",
                    "gross_amount": "300.00",
                    "discount_amount": "0",
                    "net_amount": "300.00",
                    "order_status": "17",
                    "service_type": "3",
                    "corporatename": "",
                    "order_id": 517826,
                    "service_subtype_id": 13
                },
                "orderitem": [
                    {
                        "item_id": "0",
                        "item_code": "TS1500DGHDPAE0012",
                        "itemname": "Complete Blood Count (CBC) /CBP - Whole Blood",
                        "doctor": "",
                        "quantity": "1",
                        "type": "1",
                        "gross_amount": "300.00",
                        "discount_amount": "0",
                        "net_amount": "300.00",
                        "isprescribed": "2",
                        "sampletype": "Blood",
                        "department": "Pathology",
                        "invoiceto": "1",
                        "reportto": "1",
                        "corporateinvoiceemail": "",
                        "corporatereportemail": "",
                        "reportdeliverydatefrom": "undefined-undefined-Tundefined.000Z",
                        "reportdeliverydateto": "undefined-undefined-Tundefined.000Z",
                        "vacutainer": "Yellow",
                        "unique_id": 58940142,
                        "item_status": "17"
                    }
                ],
                "ordertype": "lab",
                "order_status": {
                    "order_id": 517826,
                    "order_did": "DG-DI-19-745506",
                    "order_status": "17",
                    "created_date": "2019-02-19 10:11:59",
                    "receipts_tracker_id": 502406,
                    "workorder_id": 479537
                }
            }
        },
        {
            "_id": 517828,
            "order": {
                "patientinfo": {
                    "order_id": 517828,
                    "corporatename": null,
                    "order_status": "17",
                    "gender_pref": null,
                    "mrn": "274556",
                    "patient_id": "",
                    "name": "Aravind Komara",
                    "age": "25",
                    "gender": "2",
                    "contact": "7416674136",
                    "city": "ggyyu",
                    "landmark": "jbhjhjhj",
                    "address": "jbhjhjhj,hyd,ggyyu,hyd",
                    "pincode": "87677",
                    "popname": "",
                    "delivery_lat": 0,
                    "delivery_lng": 0,
                    "wallet_amount": 0,
                    "scheduled_date": "2019-02-15T22:00:00.000Z",
                    "gross_amount": 102,
                    "discount_amount": 0,
                    "net_amount": 95,
                    "coupon_amount": 0,
                    "voucher_amount": 0,
                    "surge_amount": 0,
                    "service_subtype_id": null,
                    "service_type": "2"
                },
                "order_status": {
                    "order_id": 517828,
                    "receipts_tracker_id": 502408,
                    "order_status": "17",
                    "created_date": "2019-02-19 10:51:42",
                    "workorder_id": 479539,
                    "order_did": "DR--190219-745508"
                },
                "orderitem": [
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAA0002",
                        "gross_amount": 45,
                        "net_amount": 40,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    },
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAE0004",
                        "gross_amount": 57,
                        "net_amount": 55,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    }
                ],
                "provider_info": [],
                "prescription_file": []
            },
            "OStatus": 17,
            "WOStatus": 17,
            "odid": "DR--190219-745508",
            "wodid": "WO-000-19-58940144",
            "wid": 479539,
            "billing": [],
            "payment_info": {
                "gross_amount": 102,
                "discount_amount": 0,
                "net_amount": 95,
                "wallet_amount": 0,
                "voucher_amount": 0,
                "coupon_amount": 0,
                "payment_code": null,
                "payment_mode": "COD",
                "payment_amount": 95,
                "payment_service": "",
                "payment_reference_id": "",
                "voucher_assoc_code": "",
                "voucher_assoc_name": null,
                "voucher_code": ""
            }
        },
        {
            "_id": 517829,
            "order": {
                "patientinfo": {
                    "order_id": 517829,
                    "corporatename": null,
                    "order_status": "17",
                    "gender_pref": null,
                    "mrn": "274556",
                    "patient_id": "",
                    "name": "Aravind Komara",
                    "age": "25",
                    "gender": "2",
                    "contact": "7416674136",
                    "city": "ggyyu",
                    "landmark": "jbhjhjhj",
                    "address": "jbhjhjhj,hyd,ggyyu,hyd",
                    "pincode": "87677",
                    "popname": "",
                    "delivery_lat": 0,
                    "delivery_lng": 0,
                    "wallet_amount": 0,
                    "scheduled_date": "2019-02-15T22:00:00.000Z",
                    "gross_amount": 102,
                    "discount_amount": 0,
                    "net_amount": 95,
                    "coupon_amount": 0,
                    "voucher_amount": 0,
                    "surge_amount": 0,
                    "service_subtype_id": null,
                    "service_type": "2"
                },
                "order_status": {
                    "order_id": 517829,
                    "receipts_tracker_id": 502409,
                    "order_status": "17",
                    "created_date": "2019-02-19 10:52:49",
                    "workorder_id": 479540,
                    "order_did": "DR--190219-745509"
                },
                "orderitem": [
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAA0002",
                        "gross_amount": 45,
                        "net_amount": 40,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    },
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAE0004",
                        "gross_amount": 57,
                        "net_amount": 55,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    }
                ],
                "provider_info": [],
                "prescription_file": []
            },
            "OStatus": 17,
            "WOStatus": 17,
            "odid": "DR--190219-745509",
            "wodid": "WO-000-19-58940145",
            "wid": 479540,
            "billing": [],
            "payment_info": {
                "gross_amount": 102,
                "discount_amount": 0,
                "net_amount": 95,
                "wallet_amount": 0,
                "voucher_amount": 0,
                "coupon_amount": 0,
                "payment_code": null,
                "payment_mode": "COD",
                "payment_amount": 95,
                "payment_service": "",
                "payment_reference_id": "",
                "voucher_assoc_code": "",
                "voucher_assoc_name": null,
                "voucher_code": ""
            }
        },
        {
            "_id": 517830,
            "order": {
                "patientinfo": {
                    "order_id": 517830,
                    "corporatename": null,
                    "order_status": "17",
                    "gender_pref": null,
                    "mrn": "274556",
                    "patient_id": "",
                    "name": "Aravind Komara",
                    "age": "25",
                    "gender": "2",
                    "contact": "7416674136",
                    "city": "ggyyu",
                    "landmark": "jbhjhjhj",
                    "address": "jbhjhjhj,hyd,ggyyu,hyd",
                    "pincode": "87677",
                    "popname": "",
                    "delivery_lat": 0,
                    "delivery_lng": 0,
                    "wallet_amount": 0,
                    "scheduled_date": "2019-02-15T22:00:00.000Z",
                    "gross_amount": 102,
                    "discount_amount": 0,
                    "net_amount": 95,
                    "coupon_amount": 0,
                    "voucher_amount": 0,
                    "surge_amount": 0,
                    "service_subtype_id": null,
                    "service_type": "2"
                },
                "order_status": {
                    "order_id": 517830,
                    "receipts_tracker_id": 502410,
                    "order_status": "17",
                    "created_date": "2019-02-19 10:53:08",
                    "workorder_id": 479541,
                    "order_did": "DR--190219-745510"
                },
                "orderitem": [
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAA0002",
                        "gross_amount": 45,
                        "net_amount": 40,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    },
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAE0004",
                        "gross_amount": 57,
                        "net_amount": 55,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    }
                ],
                "provider_info": [],
                "prescription_file": []
            },
            "OStatus": 17,
            "WOStatus": 17,
            "odid": "DR--190219-745510",
            "wodid": "WO-000-19-58940146",
            "wid": 479541,
            "billing": [],
            "payment_info": {
                "gross_amount": 102,
                "discount_amount": 0,
                "net_amount": 95,
                "wallet_amount": 0,
                "voucher_amount": 0,
                "coupon_amount": 0,
                "payment_code": null,
                "payment_mode": "COD",
                "payment_amount": 95,
                "payment_service": "",
                "payment_reference_id": "",
                "voucher_assoc_code": "",
                "voucher_assoc_name": null,
                "voucher_code": ""
            }
        },
        {
            "_id": 517831,
            "order": {
                "patientinfo": {
                    "order_id": 517831,
                    "corporatename": null,
                    "order_status": "17",
                    "gender_pref": null,
                    "mrn": "274556",
                    "patient_id": "",
                    "name": "Aravind Komara",
                    "age": "25",
                    "gender": "2",
                    "contact": "7416674136",
                    "city": "ggyyu",
                    "landmark": "jbhjhjhj",
                    "address": "jbhjhjhj,hyd,ggyyu,hyd",
                    "pincode": "87677",
                    "popname": "",
                    "delivery_lat": 0,
                    "delivery_lng": 0,
                    "wallet_amount": 0,
                    "scheduled_date": "2019-02-20T10:00:00.000Z",
                    "gross_amount": 102,
                    "discount_amount": 0,
                    "net_amount": 95,
                    "coupon_amount": 0,
                    "voucher_amount": 0,
                    "surge_amount": 0,
                    "service_subtype_id": null,
                    "service_type": "2"
                },
                "order_status": {
                    "order_id": 517831,
                    "receipts_tracker_id": 502411,
                    "order_status": "17",
                    "created_date": "2019-02-19 11:16:33",
                    "workorder_id": 479542,
                    "order_did": "DR--190219-745511"
                },
                "orderitem": [
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAA0002",
                        "gross_amount": 45,
                        "net_amount": 40,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    },
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAE0004",
                        "gross_amount": 57,
                        "net_amount": 55,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    }
                ],
                "provider_info": [],
                "prescription_file": []
            },
            "OStatus": 17,
            "WOStatus": 17,
            "odid": "DR--190219-745511",
            "wodid": "WO-000-19-58940147",
            "wid": 479542,
            "billing": [],
            "payment_info": {
                "gross_amount": 102,
                "discount_amount": 0,
                "net_amount": 95,
                "wallet_amount": 0,
                "voucher_amount": 0,
                "coupon_amount": 0,
                "payment_code": null,
                "payment_mode": "COD",
                "payment_amount": 95,
                "payment_service": "",
                "payment_reference_id": "",
                "voucher_assoc_code": "",
                "voucher_assoc_name": null,
                "voucher_code": ""
            }
        },
        {
            "_id": 517832,
            "order": {
                "patientinfo": {
                    "order_id": 517832,
                    "corporatename": null,
                    "order_status": "1",
                    "gender_pref": null,
                    "mrn": "256131",
                    "patient_id": "",
                    "name": "Prabhudeep Birudu",
                    "age": "25",
                    "gender": "2",
                    "contact": "7989963651",
                    "city": "Hyderabad",
                    "landmark": "Kompally, Hyderabad, Telangana, India",
                    "address": "Kompally, Hyderabad, Telangana, India,kompally,Hyderabad,Telangana",
                    "pincode": "500014",
                    "popname": "SUCHITRA -POP",
                    "delivery_lat": 17.5428814,
                    "delivery_lng": 78.4814473,
                    "wallet_amount": 0,
                    "scheduled_date": "2019-02-20T10:00:00.000Z",
                    "gross_amount": 102,
                    "discount_amount": 0,
                    "net_amount": 95,
                    "coupon_amount": 0,
                    "voucher_amount": 0,
                    "surge_amount": 0,
                    "service_subtype_id": null,
                    "service_type": "2"
                },
                "order_status": {
                    "order_id": 517832,
                    "receipts_tracker_id": 502412,
                    "order_status": "1",
                    "created_date": "2019-02-19 11:25:40",
                    "workorder_id": 479543,
                    "order_did": "DR--190219-745512",
                    "mhoname": "My DDO"
                },
                "orderitem": [
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAA0002",
                        "gross_amount": 45,
                        "net_amount": 40,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    },
                    {
                        "category": null,
                        "subcategory_id": "",
                        "item_code": "TS1801SPHAFAE0004",
                        "gross_amount": 57,
                        "net_amount": 55,
                        "wallet_amount": 0,
                        "voucher_amount": 0,
                        "markup_amount": 0,
                        "cli_amount": 0,
                        "is_cashless": "",
                        "coupon_amount": 0,
                        "itemname": null,
                        "quantity": "",
                        "item_mrp": null,
                        "pharmaname": "",
                        "prescription_required": null,
                        "item_status": "0",
                        "packsize": null,
                        "manufacturer_id": null,
                        "manufacturer": null,
                        "type": ""
                    }
                ],
                "provider_info": [
                    {
                        "associate_id": "PL00000000000100",
                        "associate_branch_id": "3316",
                        "associate_name": null,
                        "associate_address": null,
                        "associate_location": null,
                        "associate_latitude": null,
                        "associate_longitude": null,
                        "associate_contact_number": null,
                        "associate_email_id": null,
                        "associate_website_url": null,
                        "associate_license_number": null,
                        "associate_skill": null,
                        "officer_contact_number": null
                    }
                ],
                "prescription_file": []
            },
            "OStatus": 1,
            "WOStatus": 1,
            "odid": "DR--190219-745512",
            "wodid": "WO-000-19-58940148",
            "wid": 479543,
            "billing": [],
            "payment_info": {
                "gross_amount": 102,
                "discount_amount": 0,
                "net_amount": 95,
                "wallet_amount": 0,
                "voucher_amount": 0,
                "coupon_amount": 0,
                "payment_code": null,
                "payment_mode": "COD",
                "payment_amount": 95,
                "payment_service": "",
                "payment_reference_id": "",
                "voucher_assoc_code": "",
                "voucher_assoc_name": null,
                "voucher_code": ""
            }
        },
        {
            "_id": 522880,
            "OStatus": 5,
            "WOStatus": 5,
            "odid": "DG-DI-19-759671",
            "wodid": "WO-000-19-1465430",
            "wid": 496397,
            "order": {
                "patientinfo": {
                    "mrn": "274723",
                    "patient_id": "312251",
                    "name": "Test Test",
                    "age": "49Y",
                    "gender": "2",
                    "contact": "9701702701",
                    "landmark": "NA",
                    "address": "nxjx, Mindspace Rd, Rolling Hills, P Janardhan Reddy Nagar, Gachibowli, Hyderabad, Telangana 500081, Indian, Gachibowli, Mindspace Rd, Rolling Hills, P Janardhan Reddy Nagar, Gachibowli, Hyderabad, Telangana 500081, Indian, Hyderabad, Telangana, 500081",
                    "delivery_lat": "17.4459607",
                    "pincode": "500081",
                    "delivery_lng": "78.3654487",
                    "scheduled_date": "2019-02-19T14:42:54.000Z",
                    "gross_amount": 150,
                    "discount_amount": 0,
                    "net_amount": 150,
                    "order_status": "5",
                    "service_type": "3",
                    "wallet_amount": 0,
                    "voucher_amount": 0,
                    "corporatename": null,
                    "order_id": 522880,
                    "service_subtype_id": "13",
                    "popname": "MADHAPUR - SUPER POP",
                    "skill_id": "1"
                },
                "order_status": {
                    "order_id": 522880,
                    "order_did": "DG-DI-19-759671",
                    "order_status": "5",
                    "created_date": "2019-02-19 14:42:54",
                    "receipts_tracker_id": 696645,
                    "workorder_id": 496397,
                    "mhoname": "My PHO"
                },
                "orderitem": [
                    {
                        "item_id": "TS1500DGHDBAB0006",
                        "item_code": "TS1500DGHDBAB0006",
                        "itemname": "Random Blood Sugar - RBS - Plasma",
                        "doctor": null,
                        "coupon": "",
                        "quantity": 1,
                        "type": "1",
                        "gross_amount": "150",
                        "discount_amount": 0,
                        "net_amount": "150",
                        "item_status": "0",
                        "service_type": 3,
                        "invoiceto": null,
                        "reportto": null,
                        "corporateinvoiceemail": null,
                        "corporatereportemail": null,
                        "vacutainer": "Yellow",
                        "voucherApportionedAmount": "0",
                        "reportdeliverydatefrom": "2019-02-21T14:42:00.000Z",
                        "reportdeliverydateto": "2019-02-21T15:42:00.000Z",
                        "sampletype": "",
                        "department": "lab",
                        "prescription_image": "",
                        "unique_id": 1465431
                    }
                ],
                "ordertype": "lab",
                "prescription_file": null,
                "provider_info": [
                    {
                        "associate_id": "PL00000000000100",
                        "associate_branch_id": "3316",
                        "associate_name": null,
                        "associate_address": null,
                        "associate_location": null,
                        "associate_latitude": null,
                        "associate_longitude": null,
                        "associate_contact_number": null,
                        "associate_email_id": null,
                        "associate_website_url": null,
                        "associate_license_number": null,
                        "associate_skill": null
                    }
                ],
                "vendorinfo": {
                    "VendorCode": "DC00000009990145",
                    "VendorName": "lucid diagnostics lab",
                    "VendorLoc": ""
                }
            },
            "billing": {
                "billing_did": "B-000-19-372928"
            }
        },
        {
            "_id": 517833,
            "OStatus": 17,
            "WOStatus": 17,
            "odid": "FC-DI-19-745513",
            "wodid": "WO-000-19-58940149",
            "wid": 479544,
            "order": {
                "patientinfo": {
                    "mrn": "275263",
                    "patient_id": "312791",
                    "name": "Latha  Mrs",
                    "age": "55Y",
                    "gender": "1",
                    "contact": "9291367048",
                    "landmark": "IDPL Colony, Balanagar, Hyderabad, Telangana, India",
                    "pincode": "500037",
                    "address": "a-85 idpl colony near baba temple",
                    "city": "Hyderabad",
                    "popname": "BOWENPALLY - SUPER POP",
                    "delivery_lat": "17.481533900000000000",
                    "delivery_lng": "78.455301299999970000",
                    "scheduled_date": "",
                    "gross_amount": "13400.00",
                    "discount_amount": 0,
                    "net_amount": "13400.00",
                    "corporatename": "",
                    "wallet_amount": "0",
                    "order_id": 517833,
                    "order_status": "17",
                    "service_type": "4",
                    "service_subtype_id": "27",
                    "skill_id": "1"
                },
                "order_status": {
                    "order_id": 517833,
                    "order_did": "FC-DI-19-745513",
                    "order_status": "17",
                    "created_date": "2019-02-19 17:08:37",
                    "receipts_tracker_id": 502413,
                    "workorder_id": 479544
                },
                "orderitem": [
                    {
                        "item_id": "TS1500FACRIMR0007",
                        "item_code": "TS1500FACRIMR0007",
                        "itemname": "MRI BOTH ARM",
                        "doctor": "",
                        "quantity": "1",
                        "type": "2",
                        "gross_amount": "13400",
                        "discount_amount": "0",
                        "net_amount": "13400",
                        "isprescribed": "2",
                        "invoiceto": "1",
                        "reportto": "1",
                        "corporateinvoiceemail": "",
                        "corporatereportemail": "",
                        "item_status": "17"
                    }
                ],
                "ordertype": "rad"
            }
        },
        {
            "_id": 517834,
            "OStatus": 17,
            "WOStatus": 17,
            "odid": "FC-DI-19-745514",
            "wodid": "WO-000-19-58940150",
            "wid": 479545,
            "order": {
                "patientinfo": {
                    "mrn": "275263",
                    "patient_id": "312791",
                    "name": "Latha  Mrs",
                    "age": "55Y",
                    "gender": "1",
                    "contact": "9291367048",
                    "landmark": "IDPL Colony, Balanagar, Hyderabad, Telangana, India",
                    "pincode": "500037",
                    "address": "a-85 idpl colony near baba temple",
                    "city": "Hyderabad",
                    "popname": "BOWENPALLY - SUPER POP",
                    "delivery_lat": "17.481533900000000000",
                    "delivery_lng": "78.455301299999970000",
                    "scheduled_date": "",
                    "gross_amount": "7000.00",
                    "discount_amount": 0,
                    "net_amount": "7000.00",
                    "corporatename": "",
                    "wallet_amount": "0",
                    "order_id": 517834,
                    "order_status": "17",
                    "service_type": "4",
                    "service_subtype_id": "27",
                    "skill_id": "1"
                },
                "order_status": {
                    "order_id": 517834,
                    "order_did": "FC-DI-19-745514",
                    "order_status": "17",
                    "created_date": "2019-02-19 17:11:16",
                    "receipts_tracker_id": 502414,
                    "workorder_id": 479545
                },
                "orderitem": [
                    {
                        "item_id": "TS1500FACRIMR0008",
                        "item_code": "TS1500FACRIMR0008",
                        "itemname": "MRI LEFT ARM",
                        "doctor": "",
                        "quantity": "1",
                        "type": "2",
                        "gross_amount": "7000",
                        "discount_amount": "0",
                        "net_amount": "7000",
                        "isprescribed": "2",
                        "invoiceto": "1",
                        "reportto": "1",
                        "corporateinvoiceemail": "",
                        "corporatereportemail": "",
                        "item_status": "17"
                    }
                ],
                "ordertype": "rad"
            }
        },
        {
            "_id": 517835,
            "OStatus": 17,
            "WOStatus": 17,
            "odid": "FC-DI-19-745515",
            "wodid": "WO-000-19-58940151",
            "wid": 479546,
            "order": {
                "patientinfo": {
                    "mrn": "275261",
                    "patient_id": "312789",
                    "name": "emailpf  .",
                    "age": "24Y",
                    "gender": "2",
                    "contact": "9000041450",
                    "landmark": "Chandanagar",
                    "pincode": "500050",
                    "address": "Chandanagar Bus Stop",
                    "city": "Hyderabad",
                    "popname": "MADINAGUDA - SUPER POP",
                    "delivery_lat": "17.492400000000000000",
                    "delivery_lng": "78.341729000000000000",
                    "scheduled_date": "2019-02-20T10:00:00.000Z",
                    "gross_amount": "7250.00",
                    "discount_amount": 0,
                    "net_amount": "7250.00",
                    "corporatename": "",
                    "wallet_amount": "0",
                    "order_id": 517835,
                    "order_status": "17",
                    "service_type": "4",
                    "service_subtype_id": "27",
                    "skill_id": "1"
                },
                "order_status": {
                    "order_id": 517835,
                    "order_did": "FC-DI-19-745515",
                    "order_status": "17",
                    "created_date": "2019-02-19 17:12:07",
                    "receipts_tracker_id": 502415,
                    "workorder_id": 479546
                },
                "orderitem": [
                    {
                        "item_id": "TS1500FACRIMR0006",
                        "item_code": "TS1500FACRIMR0006",
                        "itemname": "MRI RIGHT ANKLE",
                        "doctor": "",
                        "quantity": "1",
                        "type": "2",
                        "gross_amount": 7250,
                        "discount_amount": 0,
                        "net_amount": 7250,
                        "isprescribed": "2",
                        "invoiceto": "1",
                        "reportto": "1",
                        "corporateinvoiceemail": "",
                        "corporatereportemail": "",
                        "item_status": "17",
                        "vacutainer": null,
                        "reportdeliverydatefrom": "1970-01-01T05:30:00.000Z",
                        "reportdeliverydateto": "1970-01-01T05:30:00.000Z"
                    }
                ],
                "ordertype": "rad"
            }
        }
    ],
    "countn": 10
}';
$tableRecards = array('totalcount' => 10);
//$request = new http\Env\Request();
//print_r($request->getBody()); exit;
$jsonDecode = json_decode($perpage);
$request = json_decode(file_get_contents("php://input"));
if($request->pagination == false){
    $tableRecards['data'] = $jsonDecode->data;
echo json_encode($tableRecards); exit;
}
$limit = $request->limit;
$offset = $request->skip;
$offset = $offset - 1;
$jsonDncode = array($jsonDecode->data[$offset]);
$tableRecards['data'] = $jsonDncode;
echo json_encode($tableRecards); exit;


?>